name: Tests

on:
  push:

jobs:
  test:
    name: Tests Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn

      - name: yarn install
        run: yarn install

      - name: Jest
        run: yarn run test

      - name: Coverage
        run: yarn run test-with-coverage
